service: bigvue-home-assigment-3

frameworkVersion: '3'

custom:
  bucketName: ${self:service}-bucket

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  environment:
          BUCKET_NAME: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:Put*"
      Resource: arn:aws:s3:::${self:custom.bucketName}/*

plugins:
  - serverless-offline

resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: PublicRead
        
functions:
  take_screenshot:
    handler: src/handler.handler
    events:
      - http:
          path: /
          method: post
          cors: true
    timeout: 60